### ISSUE TITLE
Hold Call not working

### ISSUE THREAD

**Issue by raycalleja** [lehel-twilio/plugin-dialpad#18]
Since last Friday (04-05-2109) we are unable to place an outbound call on hold. The problem appears to be in the CustomActions.js actions for HoldCall & UnholdCall. 

When trying to set the constant "const conference = task.attributes.conference.sid", the system responds with the error "Cannot read property 'sid' of undefined".

Upon further investigation, I found that the "payload.task.attributes.conference" variable does not exist.

**Comment by johnfischelli** [comment]
Hi @raycalleja, I have a PR open to fix this issue: see #19 - obviously it will be better once its merged in, but you could at least test and play with this fix in advance (the changes are small).
