### ISSUE TITLE
Plugin shows empty screen

### ISSUE THREAD

**Issue by harutyunyan611** [lehel-twilio/plugin-dialpad#24]
![image](https://user-images.githubusercontent.com/20282662/58512847-2a45fb00-81af-11e9-8deb-95961fb89f1d.png)

Plugin throws "TypeError: Cannot read property '@global' of undefined."

Can anybody help me?

**Comment by patrickappelman** [comment]
Following.  We are experiencing the same thing... this just began last night for us.

**Comment by patrickappelman** [comment]
@harutyunyan611 I was experiencing the same issue today.  My Flex UI was set to version 1.8.2 with "Automatic Updates" checked.  I unchecked "Automatic Updates" and upgraded the Flex UI to version 1.9.1, and Dialpad began working again.

**Comment by Antonyan7** [comment]
Thanks Patrick!

**Comment by KhangNg92** [comment]
hi @patrickappelman, can you please be more specific where did you find that flex UI version and also the Automatic Updates? Thanks a lot

**Comment by patrickappelman** [comment]
Hi @KhangNg92, There is an option near the top of the admin panel in Flex. The current UI version and automatic updates can be configured here.

<img width="748" alt="Screen Shot 2019-06-08 at 12 19 32 PM" src="https://user-images.githubusercontent.com/6757952/59150359-d4135c00-89e7-11e9-82c5-adf3e7a53858.png">

**Comment by KhangNg92** [comment]
I appreciate that @patrickappelman , btw if you have sometimes, can I jump on a call with you for a 5 mins conversation? I just want to ask you something about the flex. It's just hard for me to explain through writing. Once again, I appreciate that. If you can shoot me your email, i can shoot you a link to the invitation

**Comment by KhangNg92** [comment]
I actually tried it and it works, but my version actually **1.9.2** and I think that cost the issue that it doesn't display the dialpad button 

<img width="377" alt="Screen Shot 2019-06-08 at 3 48 11 PM" src="https://user-images.githubusercontent.com/38340140/59152193-febfdd80-8a04-11e9-8f4f-55934d6c4057.png">

**Comment by lehel-twilio** [comment]
@KhangNg92 Are you running Flex locally or hosted?

**Comment by KhangNg92** [comment]
hi @lehel-twilio hel, I tried by changing the current version to the newest one on the hosted and it works for me but just in **Light theme** so whenever you change to **Dark Theme** the background doesn't connect to the theme and the numbers gone like the picture above. I appreciate if you can come up with any helps

**Comment by lehel-twilio** [comment]
The light theme vs dark theme is a separate issue. I would like to close out this issue as I believe it is resolved.

FYI, I am working on rewriting the entire dialpad plugin. In the new version, I will add support for the dark theme as well. There is already an issue open for the dark theme support.
