### ISSUE TITLE
Documentation Corrections

### ISSUE THREAD

**Issue by microagent** [lehel-twilio/plugin-dialpad#25]
1. It appears the Twilio Function, Flex Dialpad Create New Task, requires "Check for valid Twilio signature" be unchecked" or the call will fail - net::ERR_ABORTED 403.

2. Axios must be included as a Dependency for your Twilio Functions https://www.twilio.com/console/runtime/functions/configure

**Comment by lehel-twilio** [comment]
These updates are now included in the README.
