### ISSUE TITLE
Task Wrap-up Errors

### ISSUE THREAD

**Issue by patrickappelman** [lehel-twilio/plugin-dialpad#26]
Using Dialpad v3.2.0.  I am receiving 2 errors logged in the Debugger for every outbound call. They are fired when the "Complete" button is clicked during the task wrap up.  They also only fire if the call was actually connected, e.g. if you hang up before the caller picks up, no errors are fired.

Here are the errors I am receiving:

```
Error - 16011 - Conference Event: Error Response to Callback URL
Body: Cannot wrap up a task [Task] in workspace [Workspace] for account [AccountSid] because it is not currently assigned.
```

```
Error - 82002 - Error on Twilio Function response
Body: Cannot wrap up a task [Task] in workspace [Workspace] for account [AccountSid] because it is not currently assigned.
```

The outbound call itself works, the task is marked complete, and everything seems to be functioning properly from a user experience perspective, however the Debugger is still overflowing with error logs as we are making outbound calls.

**Comment by rcfrias** [comment]
Hi @patrickappelman , manual Wrapping was something required before, but it has been updated, so that the task enters Wrapping "state" automatically once the conference is over.  The problem with the plugin, is that it is trying to wrap the task while it is already completed.

Solution: Just remove or comment this code:

```
manager.voiceClient.on('disconnect', function(connection) {
      manager.workerClient.reservations.forEach(reservation => {
        if (reservation.task.attributes.worker_call_sid === connection.parameters.CallSid && reservation.task.taskChannelUniqueName === 'custom1' &&
              reservation.task.attributes.direction === 'outbound') {
          reservation.task.wrapUp();
        };
      });
    });
```
at the DialpadPlugin.js
*Hope it helps!
-roberto

**Comment by patrickappelman** [comment]
@rcfrias Brilliant! I am no longer receiving errors on task wrap-up. Thank you!

**Comment by sandeep-datman** [comment]
I'm facing the issue still even after commenting that piece of that code. 
![image](https://user-images.githubusercontent.com/52954968/62145483-2fd7d280-b311-11e9-88a8-1c76abdc9ef7.png)

**Comment by sandeep-datman** [comment]
Still facing the issue even after commenting that piece of code. 

![image](https://user-images.githubusercontent.com/52954968/62145671-788f8b80-b311-11e9-90c9-80967250ac37.png)
