### ISSUE TITLE
Button doesn't work with dark screen mode

### ISSUE THREAD

**Issue by KhangNg92** [lehel-twilio/plugin-dialpad#30]
good day all,

I have a little concern here that dialpad buttons don't actually work for dark screen mode plus the background itself doesn't change to the dark. Any clues would be much appreciate

![Screen Shot 2019-06-10 at 5 07 29 PM](https://user-images.githubusercontent.com/38340140/59230272-90188680-8ba2-11e9-9ffe-1002d0ab3056.png)

**Comment by lehel-twilio** [comment]
This issue is fixed in version 4.2
