### ISSUE TITLE
What's the difference with this other repo?

### ISSUE THREAD

**Issue by erperejildo** [lehel-twilio/plugin-dialpad#34]
https://github.com/trogers-twilio/plugin-dialpad.

This one fixed some issues on the UI during the call but now is older than this one. Which one should I use instead?

**Comment by trogers-twilio** [comment]
@erperejildo The Dialpad plugin on Lehel's profile is still the one to use. I forked it simply to test UI enhancements for the conference participants. I eventually plan to merge those changes back to this repo on Lehel's profile. I've just been waiting for some Flex UI changes that will alter the approach I took for fixing the conference participant actions.

**Comment by erperejildo** [comment]
Thanks for clarifying @trogers-twilio. Please, let me know over here as son as you have these changes merged

**Comment by erperejildo** [comment]
@trogers-twilio you commented some UI changes but [this API](https://github.com/trogers-twilio/plugin-dialpad/blob/master/src/functions/remove-conference-participant.js) is not on this repo: https://github.com/lehel-twilio/plugin-dialpad/tree/master/src/functions
