### ISSUE TITLE
Cannot record outbound call

### ISSUE THREAD

**Issue by erperejildo** [lehel-twilio/plugin-dialpad#36]
I'd like to record outbound calls and I tried these ways:

- Events (this works but for incoming calls):
```
flex.Actions.addListener("beforeAcceptTask", payload => {
      payload.conferenceOptions.conferenceRecord = true;
    });
```

- Param on function `create-new-task` and `call-outbound-join`:
`record: true`

I can only see inbound calls recordings

**Comment by prbenson** [comment]
I did the exact same thing using the add listener action and adding record: true on creat-new-task, call-outbound-join, and also on add-conference-participant but none of those are triggering a call recording for the outbound call.

Please advise.

**Comment by erperejildo** [comment]
@prbenson add this line in `CustomActions.js`:
reservation.call(
            reservation.task.attributes.from,
            `https://${runtimeDomain}/agent-outbound-join?taskSid=${
              payload.task.taskSid
            }`,
            {
              accept: true
              record: "record-from-answer"
            }
          );

**Comment by prbenson** [comment]
@erperejildo thank you!  That did the trick!
