### ISSUE TITLE
Uncaught (in promise) SyntaxError: Unexpected end of JSON input at plugin-dialpad.js:1

### ISSUE THREAD

**Issue by NekoLopez** [lehel-twilio/plugin-dialpad#40]
I'm newbie on this, I followed all the steps and when I want to make phone calls it shows me this error:

![Screen Shot 2019-07-10 at 3 17 33 PM](https://user-images.githubusercontent.com/31256953/61001793-edc8fb80-a325-11e9-8ff0-34eee7a9fd8a.png)

Flex version 1.11.1 (same happens with 1.10.0)
plugin-dialpad version 4.0

How can I fix it?
I'd like your help.

**Comment by lehel-twilio** [comment]
Try running the plugin locally. You will get a lot more useful logging, including which line is throwing the error.

**Comment by NekoLopez** [comment]
> Try running the plugin locally. You will get a lot more useful logging, including which line is throwing the error.

Yes! You were right, I had to create all the functions according to functions folder, but now when I want to make a phone call it's showing an error on Twilio debugger: Got HTTP 500 response from https://*****.twil.io/call-outbound-join Error: 'From' phone number not verified. My Twilio phone number is not from USA. How can I fix it?

![008](https://user-images.githubusercontent.com/31256953/61151628-019e6a00-a4ac-11e9-81b0-79791d538001.png)

![009](https://user-images.githubusercontent.com/31256953/61151651-0a8f3b80-a4ac-11e9-8c03-89f0e098a704.png)

**Comment by lehel-twilio** [comment]
Is the from number is one of the phone numbers in your Twilio account?

**Comment by NekoLopez** [comment]
> Is the from number is one of the phone numbers in your Twilio account?

Yes, It's my twilio phone number but It's not a phone number of USA, It's from another country.

**Comment by NekoLopez** [comment]
> Is the from number is one of the phone numbers in your Twilio account?

Yes, It's my twilio phone number but It's not a phone number of USA, It's from another country.

![010](https://user-images.githubusercontent.com/31256953/61240715-7a4d3280-a707-11e9-83cc-22dd37564009.png)

" 5117009040" is the phone number of Peru I've purchased in my Twilio account, and I make calls to other phone numbers of Peru. 
Is there something additional I have to do?

**Comment by NekoLopez** [comment]
Ok, I fixed it adding this in Create New Task function: 

`const numbx = "+" + event.From;
const wnumbx = numbx.replace(/\s/g,'');
console.log(wnumbx);
const numbt = "+" + event.To;
const wnumbt = numbt.replace(/\s/g,'');
console.log(wnumbt);`
`client
  .taskrouter.workspaces(workspace)
  .tasks
  .create(
    {
      attributes: JSON.stringify(
        {
          to: wnumbt,
          direction: 'outbound',
          name: 'MY COMPANY',
          from: wnumbx,`
