### ISSUE TITLE
Conflict with Salesforce click-to-call

### ISSUE THREAD

**Issue by erperejildo** [lehel-twilio/plugin-dialpad#42]
I have Flex integrated within SF and I can click on phone numbers to call from SF. That was working fine but as soon as I installed the dialpad, this function is overwriting the normal behaviour of outbound calls:
`Actions.replaceAction("AcceptTask", (payload, original) => {`

So when it runs `original(payload);` it displays the normal accept and cancel buttons on my task (outbound call) when this call is auto accepted by default. It also gets stuck and if I click any of these buttons nothing happens. I have to go to the console and manually remove it.

**Comment by lehel-twilio** [comment]
This is a known issue. Actions in Flex can only be replaced once. Both plugins are replacing the same action. The only solution would be to use the open-source Salesforce integration (https://github.com/lehel-twilio/plugin-sfdc). This way you have control over which plugin replaces the AcceptTask.

**Comment by erperejildo** [comment]
At the end what I did was replaced the function we have for click-to-call and use the one from dialpad instead.
It was a bit messy at beginning because that `AccepTask` is also replacing other channels we have but at least it's working now.

This is my action:
```
Actions.replaceAction("AcceptTask", (payload, original) => {
    return new Promise((resolve, reject) => {
      const reservation = payload.task.sourceObject;
      if (
        payload.task.taskChannelUniqueName === "voice" &&
        payload.task.attributes.direction === "outbound"
      ) {
        //Join existing conference as 3rd participant
        if (typeof reservation.task.attributes.conferenceSid !== "undefined") {
          reservation.call(
            reservation.task.attributes.from,
            `https://${runtimeDomain}/agent-join-conference?conferenceSid=${
              reservation.task.attributes.conferenceSid
            }`,
            {
              accept: true
            }
          );
        } else {
          // dialpad outbound
          reservation.call(
            reservation.task.attributes.from,
            `https://${runtimeDomain}/agent-outbound-join?taskSid=${
              payload.task.taskSid
            }`,
            {
              accept: true
              //record: "record-from-answer"
            }
          );
        }
      } else {
        original(payload);
      }
      resolve();
    });
  });
```
